// Code generated by MockGen. DO NOT EDIT.
// Source: ../pool/manager.go
//
// Generated by this command:
//
//	mockgen -source=../pool/manager.go -destination=./pool.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
