// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {config} from '../models';
import {processor} from '../models';
import {watcher} from '../models';
import {context} from '../models';

export function AddFilesToQueue():Promise<void>;

export function ApplyPendingConfig():Promise<void>;

export function CancelJob(arg1:string):Promise<void>;

export function CancelUpload():Promise<void>;

export function ClearQueue():Promise<void>;

export function DebugQueueItem(arg1:string):Promise<Record<string, any>>;

export function DiscardPendingConfig():Promise<void>;

export function DownloadLogFile():Promise<void>;

export function DownloadNZB(arg1:string):Promise<void>;

export function GetAppStatus():Promise<backend.AppStatus>;

export function GetAppliedConfig():Promise<config.ConfigData>;

export function GetAutoPauseReason():Promise<string>;

export function GetConfig():Promise<config.ConfigData>;

export function GetConfigPath():Promise<string>;

export function GetLoggingStatus():Promise<Record<string, any>>;

export function GetLogs():Promise<string>;

export function GetLogsPaginated(arg1:number,arg2:number):Promise<string>;

export function GetMigrationStatus():Promise<Record<string, any>>;

export function GetNZB(arg1:string):Promise<string>;

export function GetNntpPoolMetrics():Promise<backend.NntpPoolMetrics>;

export function GetOutputDirectory():Promise<string>;

export function GetPendingConfigStatus():Promise<Record<string, any>>;

export function GetProcessorStatus():Promise<backend.ProcessorStatus>;

export function GetQueueItems(arg1:backend.PaginationParams):Promise<backend.PaginatedQueueResult>;

export function GetQueueStats():Promise<backend.QueueStats>;

export function GetRunningJobs():Promise<Array<processor.RunningJobItem>>;

export function GetRunningJobsDetails():Promise<Array<processor.RunningJobDetails>>;

export function GetWatchDirectory():Promise<string>;

export function GetWatcherStatus():Promise<watcher.WatcherStatusInfo>;

export function HandleDroppedFiles(arg1:Array<string>):Promise<void>;

export function HasPendingConfigChanges():Promise<boolean>;

export function IsLegacyDatabase():Promise<boolean>;

export function IsProcessingAutoPaused():Promise<boolean>;

export function IsProcessingPaused():Promise<boolean>;

export function IsUploading():Promise<boolean>;

export function MigrateTo(arg1:number):Promise<void>;

export function NavigateToDashboard():Promise<void>;

export function NavigateToSettings():Promise<void>;

export function PauseProcessing():Promise<void>;

export function RecreateDatabase():Promise<void>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function ResetDatabase():Promise<void>;

export function ResumeProcessing():Promise<void>;

export function RetryJob(arg1:string):Promise<void>;

export function RetryScript(arg1:string):Promise<void>;

export function RollbackMigration():Promise<void>;

export function RunMigrations():Promise<void>;

export function SaveConfig(arg1:config.ConfigData):Promise<void>;

export function SelectConfigFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectOutputDirectory():Promise<string>;

export function SelectTempDirectory():Promise<string>;

export function SelectWatchDirectory():Promise<string>;

export function SetQueueItemPriority(arg1:string,arg2:number):Promise<void>;

export function SetWebEventEmitter(arg1:any):Promise<void>;

export function SetWebMode(arg1:boolean):Promise<void>;

export function SetupWizardComplete(arg1:backend.SetupWizardData):Promise<void>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestProviderConnectivity(arg1:backend.ServerData):Promise<backend.ValidationResult>;

export function TriggerScan():Promise<void>;

export function UploadFiles():Promise<void>;

export function UploadFolder(arg1:string):Promise<void>;

export function ValidateNNTPServer(arg1:backend.ServerData):Promise<backend.ValidationResult>;
