// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilesToQueue() {
  return window['go']['backend']['App']['AddFilesToQueue']();
}

export function CancelJob(arg1) {
  return window['go']['backend']['App']['CancelJob'](arg1);
}

export function CancelUpload() {
  return window['go']['backend']['App']['CancelUpload']();
}

export function ClearQueue() {
  return window['go']['backend']['App']['ClearQueue']();
}

export function DebugQueueItem(arg1) {
  return window['go']['backend']['App']['DebugQueueItem'](arg1);
}

export function DownloadNZB(arg1) {
  return window['go']['backend']['App']['DownloadNZB'](arg1);
}

export function GetAppStatus() {
  return window['go']['backend']['App']['GetAppStatus']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['backend']['App']['GetConfigPath']();
}

export function GetLogs() {
  return window['go']['backend']['App']['GetLogs']();
}

export function GetLogsPaginated(arg1, arg2) {
  return window['go']['backend']['App']['GetLogsPaginated'](arg1, arg2);
}

export function GetNZBContent(arg1) {
  return window['go']['backend']['App']['GetNZBContent'](arg1);
}

export function GetOutputDirectory() {
  return window['go']['backend']['App']['GetOutputDirectory']();
}

export function GetProcessorStatus() {
  return window['go']['backend']['App']['GetProcessorStatus']();
}

export function GetProgress() {
  return window['go']['backend']['App']['GetProgress']();
}

export function GetQueueItems() {
  return window['go']['backend']['App']['GetQueueItems']();
}

export function GetQueueStats() {
  return window['go']['backend']['App']['GetQueueStats']();
}

export function GetRunningJobDetails() {
  return window['go']['backend']['App']['GetRunningJobDetails']();
}

export function GetRunningJobs() {
  return window['go']['backend']['App']['GetRunningJobs']();
}

export function GetWatchDirectory() {
  return window['go']['backend']['App']['GetWatchDirectory']();
}

export function HandleDroppedFiles(arg1) {
  return window['go']['backend']['App']['HandleDroppedFiles'](arg1);
}

export function IsUploading() {
  return window['go']['backend']['App']['IsUploading']();
}

export function NavigateToDashboard() {
  return window['go']['backend']['App']['NavigateToDashboard']();
}

export function NavigateToSettings() {
  return window['go']['backend']['App']['NavigateToSettings']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['backend']['App']['RemoveFromQueue'](arg1);
}

export function RetryJob(arg1) {
  return window['go']['backend']['App']['RetryJob'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SelectConfigFile() {
  return window['go']['backend']['App']['SelectConfigFile']();
}

export function SelectOutputDirectory() {
  return window['go']['backend']['App']['SelectOutputDirectory']();
}

export function SelectWatchDirectory() {
  return window['go']['backend']['App']['SelectWatchDirectory']();
}

export function SetQueueItemPriority(arg1, arg2) {
  return window['go']['backend']['App']['SetQueueItemPriority'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function UploadFiles() {
  return window['go']['backend']['App']['UploadFiles']();
}
