// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {backend} from '../models';
import {processor} from '../models';

export function AddFilesToQueue():Promise<void>;

export function CancelJob(arg1:string):Promise<void>;

export function CancelUpload():Promise<void>;

export function ClearQueue():Promise<void>;

export function DebugQueueItem(arg1:string):Promise<Record<string, any>>;

export function DownloadNZB(arg1:string):Promise<void>;

export function GetAppStatus():Promise<Record<string, any>>;

export function GetConfig():Promise<config.ConfigData>;

export function GetConfigPath():Promise<string>;

export function GetNZBContent(arg1:string):Promise<string>;

export function GetOutputDirectory():Promise<string>;

export function GetProcessorStatus():Promise<Record<string, any>>;

export function GetProgress():Promise<backend.ProgressTracker>;

export function GetQueueItems():Promise<Array<backend.QueueItem>>;

export function GetQueueStats():Promise<Record<string, any>>;

export function GetRunningJobDetails():Promise<Array<processor.RunningJobDetails>>;

export function GetRunningJobs():Promise<Array<processor.RunningJobItem>>;

export function GetWatchDirectory():Promise<string>;

export function IsUploading():Promise<boolean>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.ConfigData):Promise<void>;

export function SelectConfigFile():Promise<string>;

export function SelectOutputDirectory():Promise<string>;

export function SelectWatchDirectory():Promise<string>;

export function SetQueueItemPriority(arg1:string,arg2:number):Promise<void>;

export function UploadFiles():Promise<void>;
