// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilesToQueue() {
  return window['go']['backend']['App']['AddFilesToQueue']();
}

export function ApplyPendingConfig() {
  return window['go']['backend']['App']['ApplyPendingConfig']();
}

export function CancelJob(arg1) {
  return window['go']['backend']['App']['CancelJob'](arg1);
}

export function CancelUpload() {
  return window['go']['backend']['App']['CancelUpload']();
}

export function ClearQueue() {
  return window['go']['backend']['App']['ClearQueue']();
}

export function DebugQueueItem(arg1) {
  return window['go']['backend']['App']['DebugQueueItem'](arg1);
}

export function DiscardPendingConfig() {
  return window['go']['backend']['App']['DiscardPendingConfig']();
}

export function DownloadLogFile() {
  return window['go']['backend']['App']['DownloadLogFile']();
}

export function DownloadNZB(arg1) {
  return window['go']['backend']['App']['DownloadNZB'](arg1);
}

export function GetAppStatus() {
  return window['go']['backend']['App']['GetAppStatus']();
}

export function GetAppliedConfig() {
  return window['go']['backend']['App']['GetAppliedConfig']();
}

export function GetAutoPauseReason() {
  return window['go']['backend']['App']['GetAutoPauseReason']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['backend']['App']['GetConfigPath']();
}

export function GetLoggingStatus() {
  return window['go']['backend']['App']['GetLoggingStatus']();
}

export function GetLogs() {
  return window['go']['backend']['App']['GetLogs']();
}

export function GetLogsPaginated(arg1, arg2) {
  return window['go']['backend']['App']['GetLogsPaginated'](arg1, arg2);
}

export function GetMigrationStatus() {
  return window['go']['backend']['App']['GetMigrationStatus']();
}

export function GetNZB(arg1) {
  return window['go']['backend']['App']['GetNZB'](arg1);
}

export function GetNntpPoolMetrics() {
  return window['go']['backend']['App']['GetNntpPoolMetrics']();
}

export function GetOutputDirectory() {
  return window['go']['backend']['App']['GetOutputDirectory']();
}

export function GetPendingConfigStatus() {
  return window['go']['backend']['App']['GetPendingConfigStatus']();
}

export function GetProcessorStatus() {
  return window['go']['backend']['App']['GetProcessorStatus']();
}

export function GetQueueItems(arg1) {
  return window['go']['backend']['App']['GetQueueItems'](arg1);
}

export function GetQueueStats() {
  return window['go']['backend']['App']['GetQueueStats']();
}

export function GetRunningJobs() {
  return window['go']['backend']['App']['GetRunningJobs']();
}

export function GetRunningJobsDetails() {
  return window['go']['backend']['App']['GetRunningJobsDetails']();
}

export function GetWatchDirectory() {
  return window['go']['backend']['App']['GetWatchDirectory']();
}

export function GetWatcherStatus() {
  return window['go']['backend']['App']['GetWatcherStatus']();
}

export function HandleDroppedFiles(arg1) {
  return window['go']['backend']['App']['HandleDroppedFiles'](arg1);
}

export function HasPendingConfigChanges() {
  return window['go']['backend']['App']['HasPendingConfigChanges']();
}

export function IsLegacyDatabase() {
  return window['go']['backend']['App']['IsLegacyDatabase']();
}

export function IsProcessingAutoPaused() {
  return window['go']['backend']['App']['IsProcessingAutoPaused']();
}

export function IsProcessingPaused() {
  return window['go']['backend']['App']['IsProcessingPaused']();
}

export function IsUploading() {
  return window['go']['backend']['App']['IsUploading']();
}

export function MigrateTo(arg1) {
  return window['go']['backend']['App']['MigrateTo'](arg1);
}

export function NavigateToDashboard() {
  return window['go']['backend']['App']['NavigateToDashboard']();
}

export function NavigateToSettings() {
  return window['go']['backend']['App']['NavigateToSettings']();
}

export function PauseProcessing() {
  return window['go']['backend']['App']['PauseProcessing']();
}

export function RecreateDatabase() {
  return window['go']['backend']['App']['RecreateDatabase']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['backend']['App']['RemoveFromQueue'](arg1);
}

export function ResetDatabase() {
  return window['go']['backend']['App']['ResetDatabase']();
}

export function ResumeProcessing() {
  return window['go']['backend']['App']['ResumeProcessing']();
}

export function RetryJob(arg1) {
  return window['go']['backend']['App']['RetryJob'](arg1);
}

export function RetryScript(arg1) {
  return window['go']['backend']['App']['RetryScript'](arg1);
}

export function RollbackMigration() {
  return window['go']['backend']['App']['RollbackMigration']();
}

export function RunMigrations() {
  return window['go']['backend']['App']['RunMigrations']();
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SelectConfigFile() {
  return window['go']['backend']['App']['SelectConfigFile']();
}

export function SelectFolder() {
  return window['go']['backend']['App']['SelectFolder']();
}

export function SelectOutputDirectory() {
  return window['go']['backend']['App']['SelectOutputDirectory']();
}

export function SelectTempDirectory() {
  return window['go']['backend']['App']['SelectTempDirectory']();
}

export function SelectWatchDirectory() {
  return window['go']['backend']['App']['SelectWatchDirectory']();
}

export function SetQueueItemPriority(arg1, arg2) {
  return window['go']['backend']['App']['SetQueueItemPriority'](arg1, arg2);
}

export function SetWebEventEmitter(arg1) {
  return window['go']['backend']['App']['SetWebEventEmitter'](arg1);
}

export function SetWebMode(arg1) {
  return window['go']['backend']['App']['SetWebMode'](arg1);
}

export function SetupWizardComplete(arg1) {
  return window['go']['backend']['App']['SetupWizardComplete'](arg1);
}

export function Shutdown() {
  return window['go']['backend']['App']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function TestProviderConnectivity(arg1) {
  return window['go']['backend']['App']['TestProviderConnectivity'](arg1);
}

export function UploadFiles() {
  return window['go']['backend']['App']['UploadFiles']();
}

export function UploadFolder(arg1) {
  return window['go']['backend']['App']['UploadFolder'](arg1);
}

export function ValidateNNTPServer(arg1) {
  return window['go']['backend']['App']['ValidateNNTPServer'](arg1);
}
