# https://goreleaser.com
project_name: postie

builds:
  - goos:
      - linux
    goarch:
      - amd64
    main: ./main.go
    ldflags:
      - -s -w
      - -X "main.Version={{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

# Checksum
checksum:
  name_template: 'checksums.txt'
  algorithm: sha512

# Changelog
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge branch'

snapshot:
  name_template: 'pr-{{ .Env.BRANCH_NAME  }}'

# Docker
dockers:
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Version }}-amd64'
    use: buildx
    dockerfile: ./docker/Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
    extra_files:
      - docker

docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ if .IsSnapshot }}{{ .Branch }}{{ else }}latest{{ end }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
