# https://goreleaser.com
project_name: postie

builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go
    ldflags:
      - -s -w
      - -X "main.Version={{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-linux-musl{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-linux-musl{{- end }}
        {{- end }}
      - >-
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-windows-gnu{{- end }}
        {{- end }}
universal_binaries:
  - replace: true
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

# Checksum
checksum:
  name_template: 'checksums.txt'
  algorithm: sha512

# Changelog
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge branch'

# Docker
dockers:
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
    use: buildx
    dockerfile: ./docker/Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
    extra_files:
      - docker
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
    use: buildx
    goarch: arm64
    dockerfile: ./docker/Dockerfile.aarch64
    build_flag_templates:
      - --platform=linux/arm64
    extra_files:
      - docker

docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ if .IsSnapshot }}{{ .Branch }}{{ else }}latest{{ end }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
