# https://goreleaser.com
project_name: postie

builds:
  - goos:
      - linux
    goarch:
      - amd64
    main: ./main.go
    ldflags:
      - -s -w
      - -X "main.Version={{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

# Checksum
checksum:
  name_template: 'checksums.txt'
  algorithm: sha512

# Changelog
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge branch'

snapshot:
  name_template: 'pr-{{ .Env.BRANCH_NAME  }}'
