# https://goreleaser.com
version: 2
project_name: postie-server
checksum:
  name_template: 'checksums-server.txt'
  algorithm: sha512

# Skip building binaries
builds:
  - skip: true

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge branch'

# Docker
dockers:
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
    use: buildx
    dockerfile: ./docker/Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
    extra_files:
      - docker
      - go.mod
      - go.sum
      - frontend
      - cmd
      - internal
      - pkg
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
    use: buildx
    goarch: arm64
    dockerfile: ./docker/Dockerfile.aarch64
    build_flag_templates:
      - --platform=linux/arm64
    extra_files:
      - docker
      - go.mod
      - go.sum
      - frontend
      - cmd
      - internal
      - pkg

docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ if .IsSnapshot }}{{ .Branch }}{{ else }}latest{{ end }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'