# https://goreleaser.com
project_name: postie

builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go
    ldflags:
      - -s -w
      - -X "main.Version={{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-linux-musl{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-linux-musl{{- end }}
        {{- end }}
      - >-
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-windows-gnu{{- end }}
        {{- end }}
universal_binaries:
  - replace: true
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

# Checksum
checksum:
  name_template: 'checksums.txt'
  algorithm: sha512

# Changelog
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge branch'
