# https://goreleaser.com
version: 2
project_name: postie-server
checksum:
  name_template: 'checksums-server.txt'
  algorithm: sha512

# Skip building binaries - we build inside Docker
builds:
  - skip: true

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge branch'

# Optimized Docker builds with caching
dockers:
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest-amd64'
    use: buildx
    dockerfile: ./docker/Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --cache-from=type=gha
      - --cache-to=type=gha,mode=max
      - --cache-from=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-amd64
      - --cache-to=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-amd64,mode=max
    extra_files:
      - go.mod
      - go.sum
      - frontend
      - cmd
      - internal
      - pkg
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest-arm64'
    use: buildx
    goarch: arm64
    dockerfile: ./docker/Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
      - --cache-from=type=gha
      - --cache-to=type=gha,mode=max
      - --cache-from=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-arm64
      - --cache-to=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-arm64,mode=max
    extra_files:
      - go.mod
      - go.sum
      - frontend
      - cmd
      - internal
      - pkg

docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ if .IsSnapshot }}{{ .Branch }}{{ else }}latest{{ end }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'