# Usenet servers configuration
servers:
  - host: news.example.com
    port: 119
    username: user
    password: pass
    ssl: true
    max_connections: 10
    max_connection_idle_time_in_seconds: 300
    max_connection_ttl_in_seconds: 3600
    insecure_ssl: false

# Connection pool configuration
connection_pool:
  min_connections: 5
  health_check_interval: 1m
  skip_providers_verification_on_creation: false

# Posting configuration
posting:
  max_retries: 3
  retry_delay: 5s
  article_size_in_bytes: 750000
  groups:
    - alt.bin.test
  throttle_rate: 1048576 # 1MB/s
  message_id_format: random # Options: random, ngx
  obfuscation_policy: full # Options: full, partial, none
  par2_obfuscation_policy: full # Options: full, partial, none
  group_policy: each_file # Options: all, each_file
  post_headers:
    add_ngx_header: false
    default_from: ''

# Post check configuration
post_check:
  enabled: true
  delay: 10s
  max_reposts: 1

# Par2 configuration
par2:
  redundancy: '1n*1.2' # https://github.com/animetosho/ParPar/blob/6feee4dd94bb18480f0bf08cd9d17ffc7e671b69/help-full.txt#L75
  volume_size: 153600000 # 150MB
  max_input_slices: 4000
  extra_par2_options: []

# Watcher configuration
watcher:
  size_threshold: 104857600 # 100MB
  schedule:
    start_time: '00:00'
    end_time: '23:59'
  ignore_patterns:
    - '*.tmp'
    - '*.part'
    - '*.!ut'
  min_file_size: 1048576 # 1MB
  check_interval: 5m
