name: Build

on:
  pull_request:
    branches:
      - "main"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/test
  
  build-cli:
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    runs-on: macos-13
    needs: test
    steps:
      - uses: mlugg/setup-zig@v2
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Branch
        id: branch
        uses: transferwise/sanitize-branch-name@v1

      # build CLI snapshot
      - name: Build CLI snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --snapshot --clean --config .goreleaser-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.branch.outputs.sanitized-branch-name }}

      - name: Upload CLI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postie-cli-linux
          path: dist/*linux*
