name: Build

on:
  push:
    tags:
      - "v*.*.*"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/test
  build-cli:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      # dependencies
      - uses: mlugg/setup-zig@v1
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # build CLI
      - name: Build CLI artifacts
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --config .goreleaser-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-gui-windows:
    runs-on: windows-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Wails (version from wails.json)
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # Install Bun
      - name: Install Bun
        run: npm install -g bun

      # Build Windows GUI using Wails config
      - name: Build Windows GUI
        run: wails build -platform windows/amd64 -ldflags="-extldflags=-static"
        env:
          CGO_ENABLED: 1

      # Upload Windows artifact
      - name: Upload Windows GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: postie-gui-windows-amd64
          path: build/bin

  build-gui-macos:
    runs-on: macos-13
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Wails (version from wails.json)
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # Install Bun
      - name: Install Bun
        run: npm install -g bun

      # Build macOS GUI using Wails config (Universal Binary)
      - name: Build macOS GUI
        run: wails build -platform darwin/universal
        env:
          CGO_ENABLED: 1

      # Upload macOS artifact
      - name: Upload macOS GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: postie-gui-macos-universal
          path: build/bin

  build-images:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      packages: write
    steps:
      # dependencies
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # docker login
      - name: Docker login
        if: github.event.pull_request.head.repo.fork == false
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build server and docker
      - name: Build Server artifacts
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --config .goreleaser-server.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
