name: Build

on:
  push:
    tags:
      - "v*.*.*"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/test
  build-cli:
    runs-on: macos-13
    needs: test
    permissions:
      contents: write
    steps:
      # dependencies
      - uses: mlugg/setup-zig@v2
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # build CLI
      - name: Build CLI artifacts
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --config .goreleaser-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-web-linux:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Bun for frontend build
      - name: Install Bun
        run: npm install -g bun

      # Build frontend
      - name: Build Frontend
        run: |
          cd frontend
          bun install
          bun run build

      # Build Linux web interface for multiple architectures
      - name: Build Linux Web Interface (amd64)
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -ldflags '-linkmode external -extldflags "-static"' -o build/postie-web-linux-amd64 cmd/web/main.go
        env:
          CC: gcc

      # Create archives
      - name: Create Linux Web Interface archives
        run: |
          mkdir -p dist
          tar -czf dist/postie-web-linux-amd64.tar.gz -C build postie-web-linux-amd64

      # Upload Linux Web Interface artifacts
      - name: Upload Linux Web Interface artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postie-web-linux
          path: dist/

  build-gui-windows:
    runs-on: windows-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Wails (version from wails.json)
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # Install Bun
      - name: Install Bun
        run: npm install -g bun

      # Build Windows GUI using Wails config
      - name: Build Windows GUI
        run: wails build -platform windows/amd64 -ldflags="-extldflags=-static"
        env:
          CGO_ENABLED: 1

      # Upload Windows artifact
      - name: Upload Windows GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: postie-gui-windows-amd64
          path: build/bin

  build-gui-macos:
    runs-on: macos-13
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Wails (version from wails.json)
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # Install Bun
      - name: Install Bun
        run: npm install -g bun

      # Build macOS GUI using Wails config (Universal Binary)
      - name: Build macOS GUI
        run: wails build -platform darwin/universal
        env:
          CGO_ENABLED: 1

      # Upload macOS artifact
      - name: Upload macOS GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: postie-gui-macos-universal
          path: build/bin

  build-images:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      packages: write
    steps:
      # dependencies
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # docker login
      - name: Docker login
        if: github.event.pull_request.head.repo.fork == false
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build server and docker
      - name: Build Image artifacts
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --config .goreleaser-docker.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-gui:
    runs-on: ubuntu-latest
    needs: [build-gui-windows, build-gui-macos, build-web-linux]
    permissions:
      contents: write
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download Windows GUI artifact
      - name: Download Windows GUI artifact
        uses: actions/download-artifact@v4
        with:
          name: postie-gui-windows-amd64
          path: ./windows-gui

      # Download macOS GUI artifact
      - name: Download macOS GUI artifact
        uses: actions/download-artifact@v4
        with:
          name: postie-gui-macos-universal
          path: ./macos-gui

      # Download Linux Web Interface artifact
      - name: Download Linux Web Interface artifact
        uses: actions/download-artifact@v4
        with:
          name: postie-web-linux
          path: ./linux-web

      # Create ZIP archives for GUI artifacts
      - name: Create Windows GUI archive
        run: |
          cd windows-gui
          zip -r ../postie-gui-windows-amd64.zip .

      - name: Create macOS GUI archive  
        run: |
          cd macos-gui
          zip -r ../postie-gui-macos-universal.zip .

      # Upload GUI artifacts to release
      - name: Upload GUI artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            postie-gui-windows-amd64.zip
            postie-gui-macos-universal.zip
            linux-web/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}