name: Build

on:
  push:
    tags:
      - "v*.*.*"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/test
  build-artifacts:
    runs-on: macos-13
    needs: test
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      # dependencies
      - uses: mlugg/setup-zig@v1
      # Include go and NodeJS
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # git status
      - name: Git status
        run: git status

      - name: Set up Docker
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # docker login
      - name: Docker login
        if: github.event.pull_request.head.repo.fork == false
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
