// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilesToQueue() {
  return window['go']['main']['App']['AddFilesToQueue']();
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CancelUpload() {
  return window['go']['main']['App']['CancelUpload']();
}

export function ClearQueue() {
  return window['go']['main']['App']['ClearQueue']();
}

export function DebugQueueItem(arg1) {
  return window['go']['main']['App']['DebugQueueItem'](arg1);
}

export function DownloadNZB(arg1) {
  return window['go']['main']['App']['DownloadNZB'](arg1);
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetNZBContent(arg1) {
  return window['go']['main']['App']['GetNZBContent'](arg1);
}

export function GetOutputDirectory() {
  return window['go']['main']['App']['GetOutputDirectory']();
}

export function GetProcessorStatus() {
  return window['go']['main']['App']['GetProcessorStatus']();
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function GetQueueItems() {
  return window['go']['main']['App']['GetQueueItems']();
}

export function GetQueueStats() {
  return window['go']['main']['App']['GetQueueStats']();
}

export function GetRunningJobDetails() {
  return window['go']['main']['App']['GetRunningJobDetails']();
}

export function GetRunningJobs() {
  return window['go']['main']['App']['GetRunningJobs']();
}

export function GetWatchDirectory() {
  return window['go']['main']['App']['GetWatchDirectory']();
}

export function IsUploading() {
  return window['go']['main']['App']['IsUploading']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['main']['App']['RemoveFromQueue'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectConfigFile() {
  return window['go']['main']['App']['SelectConfigFile']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SelectWatchDirectory() {
  return window['go']['main']['App']['SelectWatchDirectory']();
}

export function UploadFiles() {
  return window['go']['main']['App']['UploadFiles']();
}
